alter table [dbo].[Enem_Fact_Table]
add 
 NU_INSCRICAO_EXAM_INFO VARCHAR (150) not null default '',
 NU_INSCRICAO_PERSONAL_INFO VARCHAR (150) not null default '',
 NU_INSCRICAO_HSCS VARCHAR (150) not null default '',
 NU_INSCRICAO_PERSON_SEF VARCHAR (150) not null default '',
 NU_INSCRICAO_PERSON_INCLUSION VARCHAR (150) not null default '';

UPDATE [dbo].[Enem_Fact_Table] SET NU_INSCRICAO_EXAM_INFO = DEFAULT WHERE NU_INSCRICAO_EXAM_INFO IS NULL;
UPDATE [dbo].[Enem_Fact_Table] SET NU_INSCRICAO_PERSONAL_INFO = DEFAULT WHERE NU_INSCRICAO_PERSONAL_INFO IS NULL;
UPDATE [dbo].[Enem_Fact_Table] SET NU_INSCRICAO_HSCS = DEFAULT WHERE NU_INSCRICAO_HSCS IS NULL;
UPDATE [dbo].[Enem_Fact_Table] SET NU_INSCRICAO_PERSON_SEF = DEFAULT WHERE NU_INSCRICAO_PERSON_SEF IS NULL;
UPDATE [dbo].[Enem_Fact_Table] SET NU_INSCRICAO_PERSON_INCLUSION = DEFAULT WHERE NU_INSCRICAO_PERSON_INCLUSION IS NULL;


alter table [dbo].[Enem_Fact_Table]
alter column NU_INSCRICAO_EXAM_INFO VARCHAR (150) not null;

alter table [dbo].[Enem_Fact_Table]
alter column NU_INSCRICAO_PERSONAL_INFO VARCHAR (150) not null;

alter table [dbo].[Enem_Fact_Table]
alter column NU_INSCRICAO_HSCS VARCHAR (150) not null;
 
alter table [dbo].[Enem_Fact_Table]
alter column NU_INSCRICAO_PERSON_SEF VARCHAR (150) not null;
 
alter table [dbo].[Enem_Fact_Table]
alter column NU_INSCRICAO_PERSON_INCLUSION VARCHAR (150) not null;  
 
 ALTER TABLE [dbo].[Enem_Fact_Table]
    ADD CONSTRAINT pk_FactConstraint PRIMARY KEY (NU_INSCRICAO_EXAM_INFO,NU_INSCRICAO_PERSONAL_INFO,NU_INSCRICAO_HSCS,NU_INSCRICAO_SEF,NU_INSCRICAO_INCLUSION)
GO

ALTER TABLE [dbo].[Enem_Fact_Table]
   ADD CONSTRAINT FK_Join_Dim_InfoProva FOREIGN KEY (NU_INSCRICAO_EXAM_INFO)
      REFERENCES dbo.Dimension_Table_Info_Prova (NU_INSCRICAO_EXAM_INFO)
      ON DELETE CASCADE
      ON UPDATE CASCADE
	  
ALTER TABLE [dbo].[Enem_Fact_Table]
   ADD CONSTRAINT FK_Join_Dim_InfoPessoa FOREIGN KEY (NU_INSCRICAO_PERSONAL_INFO)
      REFERENCES dbo.Dimension_Table_Info_Pessoal (NU_INSCRICAO_PERSONAL_INFO)
      ON DELETE CASCADE
      ON UPDATE CASCADE
	  
ALTER TABLE [dbo].[Enem_Fact_Table]
   ADD CONSTRAINT FK_Join_Dim_STEM FOREIGN KEY (NU_INSCRICAO_HSCS)
      REFERENCES dbo.Dimension_Table_ST_EM (NU_INSCRICAO_HSCS)
      ON DELETE CASCADE
      ON UPDATE CASCADE
	  
ALTER TABLE [dbo].[Enem_Fact_Table]
   ADD CONSTRAINT FK_Join_Dim_QSE FOREIGN KEY (NU_INSCRICAO_SEF)
      REFERENCES dbo.Dimension_Table_QSE (NU_INSCRICAO_SEF)
      ON DELETE CASCADE
      ON UPDATE CASCADE
	  
ALTER TABLE [dbo].[Enem_Fact_Table]
   ADD CONSTRAINT FK_Join_Dim_Inclusao FOREIGN KEY (NU_INSCRICAO_INCLUSION)
      REFERENCES dbo.Dimension_Table_Inclusao (NU_INSCRICAO_PERSON_INCLUSION)
      ON DELETE CASCADE
      ON UPDATE CASCADE
	  
ALTER TABLE [dbo].[Enem_Fact_Table]
   ADD CONSTRAINT FK_Join_FactDim FOREIGN KEY (NU_INSCRICAO_JOIN_DIMS)
      REFERENCES jdt.Join_Dimensions (NU_INSCRICAO_JOIN_DIMS)
      ON DELETE CASCADE
      ON UPDATE CASCADE
	  
ALTER TABLE [dbo].[Enem_Fact_Table]
   ADD CONSTRAINT FK_Join_FactDim_NoInclusao FOREIGN KEY (NU_INSCRICAO_FACT_DIMS)
      REFERENCES jft.Join_FactDimensions_NoInclusion (NU_INSCRICAO_FACT_DIMS)
      ON DELETE CASCADE
      ON UPDATE CASCADE
	  
	  