CREATE TABLE[dbo].[Enem_Fact_Table]
(
[NU_INSCRICAO_EXAM_INFO]VARCHAR(150) NOT NULL ,
[NU_INSCRICAO_PERSONAL_INFO]VARCHAR(150) NOT NULL ,
[NU_INSCRICAO_HSCS]VARCHAR(150) NOT NULL ,
[NU_INSCRICAO_PERSON_SEF]VARCHAR(150) NOT NULL ,
[NU_INSCRICAO_PERSON_INCLUSION]VARCHAR(150) NOT NULL ,
[NU_INSCRICAO_JOIN_DIMS]VARCHAR(150) NOT NULL ,
[NU_INSCRICAO_FACT_DIMS]VARCHAR(150) NOT NULL ,
[NU_NOTA_CN]VARCHAR(150),
[NU_NOTA_CH]VARCHAR (150),
[NU_NOTA_LC] VARCHAR (150),
[NU_NOTA_MT]VARCHAR (150),
[NU_NOTA_REDACAO]VARCHAR (150),
[NU_NOTA_COMP1]VARCHAR (150),
[NU_NOTA_COMP2]VARCHAR (150),
[NU_NOTA_COMP3]VARCHAR (150),
[NU_NOTA_COMP4]VARCHAR (150),
[NU_NOTA_COMP5]VARCHAR (150)
); 