CREATE TABLE [dbo].[Dimension_Table_ST_EM]
(
[NU_INSCRICAO_HSCS]VARCHAR(150) NOT NULL PRIMARY KEY,
[TP_ST_CONCLUSAO]VARCHAR(150),
[TP_ANO_CONCLUIU]VARCHAR(150),
[TP_ESCOLA]VARCHAR(150),
[TP_ENSINO]VARCHAR(150),
[IN_TREINEIRO]VARCHAR(150),
[CO_ESCOLA]VARCHAR(150),
[CO_MUNICIPIO_ESC]VARCHAR(150),
[NO_MUNICIPIO_ESC]VARCHAR(150),
[CO_UF_ESC]VARCHAR(150),
[SG_UF_ESC]VARCHAR(150),
[TP_DEPENDENCIA_ADM_ESC]VARCHAR(150),
[TP_LOCALIZACAO_ESC]VARCHAR(150),
[TP_SIT_FUNC_ESC]VARCHAR(150)
); 