CREATE TABLE [dbo].[Dimension_Table_Info_Prova]
(
[NU_INSCRICAO_EXAM_INFO]VARCHAR(150) NOT NULL PRIMARY KEY,
[CO_MUNICIPIO_PROVA]VARCHAR(150),
[NO_MUNICIPIO_PROVA]VARCHAR(150),
[CO_UF_PROVA]VARCHAR(150),
[SG_UF_PROVA]VARCHAR(150),
[TP_PRESENCA_CN]VARCHAR(150),
[TP_PRESENCA_CH]VARCHAR(150),
[TP_PRESENCA_LC]VARCHAR(150),
[TP_PRESENCA_MT]VARCHAR(150),
[CO_PROVA_CN]VARCHAR(150),
[CO_PROVA_CH]VARCHAR(150),
[CO_PROVA_LC]VARCHAR(150),
[CO_PROVA_MT]VARCHAR(150),
[TP_LINGUA]VARCHAR(150),
[TP_STATUS_REDACAO]VARCHAR(150)
); 