SELECT [NU_INSCRICAO]
      ,[NU_NOTA_REDACAO]
      ,[NU_MEDIA_TOTAL_AREAS]
      ,[SG_UF_RESIDENCIA]
      ,[NU_IDADE]
      ,[TP_SEXO]
      ,[TP_ESTADO_CIVIL]
      ,[TP_COR_RACA]
      ,[TP_NACIONALIDADE]
      ,[NO_MUNICIPIO_NASCIMENTO]
      ,[SG_UF_NASCIMENTO]
  FROM [EnemLinkedServerSQL].[jft].[Join_FactDim_InfoProva_InfoPessoa_STEM_QSE]