/****** Script do comando SelectTopNRows de SSMS  ******/
SELECT [NU_INSCRICAO]
      ,[NU_NOTA_CN]
      ,[NU_NOTA_CH]
      ,[NU_NOTA_LC]
      ,[NU_NOTA_MT]
      ,[NU_NOTA_REDACAO]
      ,[NU_NOTA_COMP1]
      ,[NU_NOTA_COMP2]
      ,[NU_NOTA_COMP3]
      ,[NU_NOTA_COMP4]
      ,[NU_NOTA_COMP5]
      ,[TP_PRESENCA_CN]
      ,[TP_PRESENCA_CH]
      ,[TP_PRESENCA_LC]
      ,[TP_PRESENCA_MT]
      ,[TP_LINGUA]
      ,[TP_STATUS_REDACAO]
      ,[Q001]
      ,[Q002]
      ,[Q003]
      ,[Q004]
      ,[Q005]
      ,[Q006]
      ,[Q007]
      ,[Q008]
      ,[Q009]
      ,[Q010]
  FROM [EnemLinkedServerSQL].[jft].[Join_FactDim_InfoProva_InfoPessoa_STEM_QSE]