SELECT [NU_INSCRICAO]
      ,[NU_NOTA_REDACAO]
      ,[NU_MEDIA_TOTAL_AREAS]
      ,[NO_MUNICIPIO_PROVA]
      ,[SG_UF_PROVA]
      ,[TP_PRESENCA_CN]
      ,[TP_PRESENCA_CH]
      ,[TP_PRESENCA_LC]
      ,[TP_PRESENCA_MT]
      ,[CO_PROVA_CN]
      ,[CO_PROVA_CH]
      ,[CO_PROVA_LC]
      ,[CO_PROVA_MT]
      ,[TP_LINGUA]
      ,[TP_STATUS_REDACAO]
      ,[NO_MUNICIPIO_RESIDENCIA]
      ,[SG_UF_RESIDENCIA]
  FROM [EnemLinkedServerSQL].[jft].[Join_FactDim_InfoProva_InfoPessoa_STEM_QSE]