SELECT TOP (1000) [NU_INSCRICAO]
      ,[TP_ST_CONCLUSAO]
      ,[TP_ANO_CONCLUIU]
      ,[TP_ESCOLA]
      ,[TP_ENSINO]
      ,[IN_TREINEIRO]
      ,[CO_ESCOLA]
      ,[CO_MUNICIPIO_ESC]
      ,[NO_MUNICIPIO_ESC]
      ,[CO_UF_ESC]
      ,[SG_UF_ESC]
      ,[TP_DEPENDENCIA_ADM_ESC]
      ,[TP_LOCALIZACAO_ESC]
      ,[TP_SIT_FUNC_ESC]
  FROM [dbo].[Dimension_Table_ST_EM]