SELECT TOP (1000) [NU_INSCRICAO]
      ,[NU_NOTA_CN]
      ,[NU_NOTA_CH]
      ,[NU_NOTA_LC]
      ,[NU_NOTA_MT]
      ,[NU_NOTA_REDACAO]
      ,[NU_NOTA_COMP1]
      ,[NU_NOTA_COMP2]
      ,[NU_NOTA_COMP3]
      ,[NU_NOTA_COMP4]
      ,[NU_NOTA_COMP5]
  FROM [dbo].[Enem_Fact_Table]