/****** Script do comando SelectTopNRows de SSMS  ******/
SELECT [NU_INSCRICAO]
      ,[NU_NOTA_CN]
      ,[NU_NOTA_CH]
      ,[NU_NOTA_LC]
      ,[NU_NOTA_MT]
      ,[NU_NOTA_REDACAO]
      ,[NU_NOTA_COMP1]
      ,[NU_NOTA_COMP2]
      ,[NU_NOTA_COMP3]
      ,[NU_NOTA_COMP4]
      ,[NU_NOTA_COMP5]
      ,[TP_LINGUA]
      ,[TP_STATUS_REDACAO]
      ,[Q019]
      ,[Q020]
      ,[Q021]
      ,[Q022]
      ,[Q023]
      ,[Q024]
      ,[Q025]
  FROM [EnemLinkedServerSQL].[jft].[Join_FactDim_InfoProva_InfoPessoa_STEM_QSE]