SELECT [NU_INSCRICAO]
      ,[NU_NOTA_REDACAO]
      ,[NU_MEDIA_TOTAL_AREAS]
      ,[TP_ST_CONCLUSAO]
      ,[TP_ESCOLA]
      ,[TP_ENSINO]
      ,[IN_TREINEIRO]
      ,[NO_MUNICIPIO_ESC]
      ,[SG_UF_ESC]
      ,[TP_DEPENDENCIA_ADM_ESC]
      ,[TP_LOCALIZACAO_ESC]
      ,[TP_SIT_FUNC_ESC]
  FROM [EnemLinkedServerSQL].[jft].[Join_FactDim_InfoProva_InfoPessoa_STEM_QSE]