ALTER TABLE jdt.Join_Dim_QSE_InfoPessoa
   ADD CONSTRAINT FK_Join_Dim_QSE_InfoPessoa FOREIGN KEY (NU_INSCRICAO)
      REFERENCES dbo.Enem_Fact_Table (NU_INSCRICAO)
      ON DELETE CASCADE
      ON UPDATE CASCADE
	  
ALTER TABLE jdt.Join_Dim_QSE_InfoProva
   ADD CONSTRAINT FK_Join_Dim_QSE_InfoProva FOREIGN KEY (NU_INSCRICAO)
      REFERENCES dbo.Enem_Fact_Table (NU_INSCRICAO)
      ON DELETE CASCADE
      ON UPDATE CASCADE
	  
ALTER TABLE jdt.Join_Dim_QSE_STEM
   ADD CONSTRAINT FK_Join_Dim_QSE_STEM FOREIGN KEY (NU_INSCRICAO)
      REFERENCES dbo.Enem_Fact_Table (NU_INSCRICAO)
      ON DELETE CASCADE
      ON UPDATE CASCADE