ALTER TABLE jft.Join_FactDim_InfoProva
   ADD CONSTRAINT FK_JoinInfoProva_EnemFactTable FOREIGN KEY (NU_INSCRICAO)
      REFERENCES dbo.Enem_Fact_Table (NU_INSCRICAO)
      ON DELETE CASCADE
      ON UPDATE CASCADE

ALTER TABLE jft.Join_FactDim_InfoPessoal
   ADD CONSTRAINT FK_JoinInfoPessoal_EnemFactTable FOREIGN KEY (NU_INSCRICAO)
      REFERENCES dbo.Enem_Fact_Table (NU_INSCRICAO)
      ON DELETE CASCADE
      ON UPDATE CASCADE
	  
ALTER TABLE jft.Join_FactDim_QSE
   ADD CONSTRAINT FK_JoinQSE_EnemFactTable FOREIGN KEY (NU_INSCRICAO)
      REFERENCES dbo.Enem_Fact_Table (NU_INSCRICAO)
      ON DELETE CASCADE
      ON UPDATE CASCADE
	  
ALTER TABLE jft.Join_FactDim_STEM
   ADD CONSTRAINT FK_JoinSTEM_EnemFactTable FOREIGN KEY (NU_INSCRICAO)
      REFERENCES dbo.Enem_Fact_Table (NU_INSCRICAO)
      ON DELETE CASCADE
      ON UPDATE CASCADE
	  
