CREATE TABLE [dbo].[Dimension_Table_Info_Pessoal]
(
[NU_INSCRICAO]VARCHAR(150) NOT NULL PRIMARY KEY,
[CO_MUNICIPIO_RESIDENCIA]VARCHAR(150),
[NO_MUNICIPIO_RESIDENCIA]VARCHAR(150),
[CO_UF_RESIDENCIA]VARCHAR(150),
[SG_UF_RESIDENCIA]VARCHAR(150),
[NU_IDADE]VARCHAR(150),
[TP_SEXO]VARCHAR(150),
[TP_ESTADO_CIVIL]VARCHAR(150),
[TP_COR_RACA]VARCHAR(150),
[TP_NACIONALIDADE]VARCHAR(150),
[CO_MUNICIPIO_NASCIMENTO]VARCHAR(150),
[NO_MUNICIPIO_NASCIMENTO]VARCHAR(150),
[CO_UF_NASCIMENTO]VARCHAR(150),
[SG_UF_NASCIMENTO]VARCHAR(150),
   CONSTRAINT FK_Enem_Fact_Table04 FOREIGN KEY (NU_INSCRICAO)
      REFERENCES dbo.Enem_Fact_Table (NU_INSCRICAO)
      ON DELETE CASCADE
      ON UPDATE CASCADE
); 