CREATE TABLE[dbo].[Enem_Fact_Table]
(
[NU_INSCRICAO]VARCHAR(150) NOT NULL PRIMARY KEY,
[NU_NOTA_CN]VARCHAR(150),
[NU_NOTA_CH]VARCHAR (150),
[NU_NOTA_LC] VARCHAR (150),
[NU_NOTA_MT]VARCHAR (150),
[NU_NOTA_REDACAO]VARCHAR (150),
[NU_NOTA_COMP1]VARCHAR (150),
[NU_NOTA_COMP2]VARCHAR (150),
[NU_NOTA_COMP3]VARCHAR (150),
[NU_NOTA_COMP4]VARCHAR (150),
[NU_NOTA_COMP5]VARCHAR (150),
); 