SELECT TOP (1000) [NU_INSCRICAO]
      ,[CO_MUNICIPIO_PROVA]
      ,[NO_MUNICIPIO_PROVA]
      ,[CO_UF_PROVA]
      ,[SG_UF_PROVA]
      ,[TP_PRESENCA_CN]
      ,[TP_PRESENCA_CH]
      ,[TP_PRESENCA_LC]
      ,[TP_PRESENCA_MT]
      ,[CO_PROVA_CN]
      ,[CO_PROVA_CH]
      ,[CO_PROVA_LC]
      ,[CO_PROVA_MT]
      ,[TP_LINGUA]
      ,[TP_STATUS_REDACAO]
  FROM [dbo].[Dimension_Table_Info_Prova]